run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
